# Generated by Django 4.2 on 2023-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sponsor', models.CharField(max_length=50)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
            ],
        ),
    ]
